<?php
/**
 * @file
 * field_collection__contact_details.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function field_collection__contact_details_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'field_collection_item-field_contact_details-field_fc_additional_details'.
  $field_instances['field_collection_item-field_contact_details-field_fc_additional_details'] = array(
    'bundle' => 'field_contact_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please use this field to provide additional relevant details about the contact, such as their telephone number or address (if applicable).',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_fc_additional_details',
    'label' => 'Additional Details',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_contact_details-field_fc_contact_name'.
  $field_instances['field_collection_item-field_contact_details-field_fc_contact_name'] = array(
    'bundle' => 'field_contact_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Please enter the name of the individual or organisation who people can contact for further information.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_plain',
        'weight' => 0,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_plain',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_plain',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_fc_contact_name',
    'label' => 'Contact Name',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_contact_details-field_fc_email_address'.
  $field_instances['field_collection_item-field_contact_details-field_fc_email_address'] = array(
    'bundle' => 'field_contact_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'You may provide an email address, but please do obtain permission from the owner before publishing.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'email',
        'settings' => array(),
        'type' => 'email_default',
        'weight' => 2,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'email',
        'settings' => array(),
        'type' => 'email_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'email',
        'settings' => array(),
        'type' => 'email_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_fc_email_address',
    'label' => 'Email Address',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'email',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'email_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_contact_details-field_fc_partner_organisation'.
  $field_instances['field_collection_item-field_contact_details-field_fc_partner_organisation'] = array(
    'bundle' => 'field_contact_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'If this person is associated with a partner organisation, please select the organisation.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 1,
          'view_mode' => 'teaser',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 1,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'link' => 1,
        ),
        'type' => 'entityreference_label',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 1,
          'view_mode' => 'teaser',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_fc_partner_organisation',
    'label' => 'Partner Organisation',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_contact_details-field_fc_position'.
  $field_instances['field_collection_item-field_contact_details-field_fc_position'] = array(
    'bundle' => 'field_contact_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'If the contact person represents an organisation, please provide their role (Eg. Media Relations, Project Manager, Secretary, etc).',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_plain',
        'weight' => 3,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_plain',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_plain',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_fc_position',
    'label' => 'Position',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Additional Details');
  t('Contact Name');
  t('Email Address');
  t('If the contact person represents an organisation, please provide their role (Eg. Media Relations, Project Manager, Secretary, etc).');
  t('If this person is associated with a partner organisation, please select the organisation.');
  t('Partner Organisation');
  t('Please enter the name of the individual or organisation who people can contact for further information.');
  t('Please use this field to provide additional relevant details about the contact, such as their telephone number or address (if applicable).');
  t('Position');
  t('You may provide an email address, but please do obtain permission from the owner before publishing.');

  return $field_instances;
}
